### ISSUE TITLE
<in.txt grep la > out.txt | wc

### ISSUE THREAD

**Issue by Ray-cmd** [Ray-cmd/minishell#20]
doesn't work

**Comment by FizzYxWizzY** [comment]
i tried it, i see there is an infinite loop caused by the pipe.
it probably doesnt manage the output from the first cmd as input for the second cmd.

observations:
- it does read in in.txt
- it does create/write in out.txt
- "<in.txt grep la>out.txt" works alone.
- "wc" works alone too.
- problem could be from pipe interaction.
- output from cmd1 "<in.txt grep la > out.txt" (out.txt) should be an input for cmd2 "wc".

(nothing touched, just some check i did)

**Comment by Ray-cmd** [comment]
The problem has been partially corrected by PR #31. This PR fixes the "execution" part of this issue.

However, the parser is currently unable to create the tree for this command. To finish solving this issue, look at #33.

Once issue #33 is fixed, this issue should also be fixed.

**Comment by Ray-cmd** [comment]
Done

**Comment by Ray-cmd** [comment]
Done
